# Generated by Django 5.0.14 on 2026-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_calendar_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_calendar_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
