# Generated by Django 5.0.14 on 2026-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_google_calendar_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('chat', 'Chat'), ('file_upload', 'File Upload'), ('n8n', 'n8n Automation')], default='manual', max_length=20),
        ),
    ]
