# Generated by Django 4.2.7 on 2026-04-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_task_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(default='✅', help_text='Emoji icon', max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays Only'), ('custom', 'Custom Days')], default='daily', max_length=20)),
                ('custom_days', models.CharField(blank=True, help_text='Comma-separated days (0-6)', max_length=50)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('target_per_week', models.PositiveIntegerField(default=7)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('create_task', 'Create Task'), ('set_reminder', 'Set Reminder'), ('start_timer', 'Start Timer'), ('log_habit', 'Log Habit'), ('quick_note', 'Quick Note'), ('search', 'Search')], max_length=50)),
                ('transcript', models.TextField(help_text='What was said')),
                ('action_taken', models.TextField(help_text='What action was performed')),
                ('success', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Speech recognition confidence', null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_commands',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('health', 'Health & Wellness'), ('learning', 'Learning & Development'), ('work', 'Work Tasks'), ('personal', 'Personal Growth')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='Estimated time in minutes')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('suggestion_reason', models.TextField(blank=True, help_text='Why this was suggested')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=25)),
                ('break_duration_minutes', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('interrupted', 'Interrupted'), ('abandoned', 'Abandoned')], default='completed', max_length=20)),
                ('task_title', models.CharField(blank=True, help_text='What you worked on', max_length=255)),
                ('interruptions_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pomodoro_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('pomodoro_sessions', models.PositiveIntegerField(default=0)),
                ('focus_minutes', models.PositiveIntegerField(default=0)),
                ('habits_completed', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0.0, help_text='0-100 score')),
                ('mood_rating', models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('energy_level', models.PositiveIntegerField(blank=True, help_text='1-10 level', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productivity_metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.dailyhabit')),
            ],
            options={
                'db_table': 'habit_completions',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
