# Generated by Django 4.2.7 on 2026-04-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_actual_time_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kanban_status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('planner', 'AI Planner'), ('executor', 'AI Executor'), ('done', 'Done')], default='backlog', max_length=20),
        ),
    ]
