# Generated by Django 5.0.14 on 2026-04-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_kanban_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
