# Generated by Django 5.0.14 on 2026-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ntfy_topic',
            field=models.CharField(blank=True, help_text='ntfy.sh topic for push notifications', max_length=100, null=True),
        ),
    ]
