# Generated by Django 5.0.14 on 2026-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_ntfy_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ntfy_topic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_push_topic',
            field=models.CharField(blank=True, help_text='Secret ntfy.sh topic for phone notifications', max_length=100, null=True),
        ),
    ]
