# Generated by Django 5.0.14 on 2026-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_userprofile_ntfy_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your phone number including country code (e.g. +1234567890)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
