# Generated by Django 5.0.14 on 2026-04-16 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='N8NWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('webhook_url', models.URLField()),
                ('trigger_event', models.CharField(choices=[('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('chat_message', 'Chat Message Sent'), ('file_uploaded', 'File Uploaded'), ('user_registered', 'User Registered'), ('calendar_event', 'Calendar Event Created'), ('agent_triggered', 'AI Agent Triggered'), ('daily_summary', 'Daily Summary')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'n8n_workflows',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_calendar_tokens',
            },
        ),
        migrations.CreateModel(
            name='N8NLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.n8nworkflow')),
            ],
            options={
                'db_table': 'n8n_logs',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('task', 'Task'), ('calendar', 'Calendar'), ('agent', 'AI Agent'), ('n8n', 'Automation'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
